name = "imgui"
description = "Ada binding of the ImGui library"
version = "0.1.0-dev"

authors = ["Cre8or", "Michael Hardeman"]
maintainers = ["Michael Hardeman <michael.hardeman@protonmail.com>"]
maintainers-logins = ["Cre8or", "code-undisclosed"]
[[depends-on]]
openglada_glfw = "~0.9.0"
