name = "imgui_example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Michael Hardeman"]
maintainers = ["Michael Hardeman <michael.hardeman@protonmail.com>"]
maintainers-logins = ["code-undisclosed"]

executables = ["imgui_example"]
[[depends-on]]
imgui = "~0.1.0-dev"
openglada_glfw = "~0.9.0"
