name = "imgui"
description = "Ada binding of the ImGui library"
version = "0.1.0-dev"

authors = ["Cre8or"]
maintainers = ["Cre8or <enter.you.email@crea8or.com>"]
maintainers-logins = ["Cre8or"]
[[depends-on]]
openglada_glfw = "~0.9.0"
